name: CI & Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest # Linux runner needed for apt-get/cpan setup easily

    steps:
      # 1. Checkout main repository into a subdirectory 'main-repo'
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          path: main-repo # Checkout main repo into GITHUB_WORKSPACE/main-repo

      # 2. Checkout Dependencies directly into GITHUB_WORKSPACE root
      - name: Clone Unibilium Repository
        uses: actions/checkout@v3
        with:
          repository: abelkm99/unibilium
          path: unibilium # Clones into GITHUB_WORKSPACE/unibilium

      - name: Clone Libtermkey Repository
        uses: actions/checkout@v3
        with:
          repository: abelkm99/libtermkey-0.23
          path: libtermkey-0.23 # Clones into GITHUB_WORKSPACE/libtermkey-0.23

      - name: Clone Libtickit Repository
        uses: actions/checkout@v3
        with:
          repository: abelkm99/libtickit
          path: libtickit-0.4.5 # Clones into GITHUB_WORKSPACE/libtickit-0.4.5

      # Debugging: List the final workspace structure
      - name: List workspace structure
        run: ls -R $GITHUB_WORKSPACE

      # 3. Install Zig
      - name: Install Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0

      # 4. Install Perl Dependencies
      - name: Install Perl and Modules
        run: |
          sudo apt-get update -y
          sudo apt-get install -y perl cpanminus
          sudo cpanm -n Convert::Color Convert::Color::XTerm

      # 5. Build the project from within the main repo's subdirectory
      - name: Build Mac_x86 
        working-directory: ${{ github.workspace }}/main-repo # Run from where build.zig is
        run: "zig build -Dtarget=x86_64-macos -Doptimize=ReleaseSafe -Dexe_name=ziq_mac_x86"

      - name: Build MAC_ARM
        working-directory: ${{ github.workspace }}/main-repo # Run from where build.zig is
        run: "zig build -Dtarget=aarch64-macos -Doptimize=ReleaseFast -Dexe_name=ziq_mac_arm"

      - name: Build Linux_x86
        working-directory: ${{ github.workspace }}/main-repo # Run from where build.zig is
        run: "zig build -Dtarget=x86_64-linux -Doptimize=ReleaseSafe -Dexe_name=ziq_linux_x86"

      - name: Build Linux_ARM
        working-directory: ${{ github.workspace }}/main-repo # Run from where build.zig is
        run: "zig build -Dtarget=aarch64-linux -Doptimize=ReleaseSafe -Dexe_name=ziq_linux_arm"

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            main-repo/zig-out/bin/ziq_mac_arm
            main-repo/zig-out/bin/ziq_mac_x86
            main-repo/zig-out/bin/ziq_linux_arm
            main-repo/zig-out/bin/ziq_linux_x86
